import Foundation

/// Defines the user's progress, strengths, and weaknesses for personalized learning
struct LearnerProfile: Codable {
    var totalSessions: Int = 0
    var overallLevel: Double = 1.0 // 1.0 (Beginner) to 5.0 (Advanced)
    var interestTopics: [String: Double] = [:] // Topic: Weight (0.0 to 1.0)
    var vocabularyStats: [String: WordMastery] = [:] // Word: Mastery info
    var pronunciationScores: [String: Double] = [:] // Language: Average score
    var preferredTeachingStyle: TeachingStyle = .balanced
    
    // Dashboard Metrics
    var vocabularyScore: Double = 0.2
    var pronunciationScore: Double = 0.2
    var grammarScore: Double = 0.2
    var fluencyScore: Double = 0.2
    
    var streakCount: Int = 0
    var lastPracticeDate: Date?
    var recentMistakes: [Mistake] = []
    
    // Educational Continuity
    var lastLessonSummary: String?
    var lastLessonTopic: String?
    var sessionHistory: [SessionSummary]? = [] // Made optional for safer migration
    
    /// Accumulated facts about the user (goals, preferences, etc.)
    var longTermMemory: String = ""
    
    var isInitialAssessmentComplete: Bool = false
    
    /// The current structured curriculum/plan generated by Jarvis
    var teachingProgram: String?
    
    /// Pedagogical Progress
    var currentLessonIndex: Int = 1
    var completedLessonTopics: [String] = []
    
    struct SessionSummary: Codable, Identifiable {
        let id: UUID
        let date: Date
        let topic: String
        let summary: String
        let successRate: Double
    }
    
    struct WordMastery: Codable {
        var attempts: Int = 0
        var successes: Int = 0
        var lastAttempt: Date = Date()
        var successRate: Double { attempts == 0 ? 0 : Double(successes) / Double(attempts) }
    }
    
    struct Mistake: Codable, Identifiable {
        let id: UUID
        let original: String
        let correction: String
        let explanation: String
        let date: Date
        
        init(original: String, correction: String, explanation: String) {
            self.id = UUID()
            self.original = original
            self.correction = correction
            self.explanation = explanation
            self.date = Date()
        }
    }
    
    enum TeachingStyle: String, Codable {
        case supportive, strict, balanced
    }
    
    // MARK: - Custom Decoding for Migration Safety
    
    enum CodingKeys: String, CodingKey {
        case totalSessions, overallLevel, interestTopics, vocabularyStats, pronunciationScores, preferredTeachingStyle
        case vocabularyScore, pronunciationScore, grammarScore, fluencyScore
        case streakCount, lastPracticeDate, recentMistakes, lastLessonSummary, lastLessonTopic, sessionHistory
        case longTermMemory, isInitialAssessmentComplete, teachingProgram, currentLessonIndex, completedLessonTopics
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        totalSessions = try container.decodeIfPresent(Int.self, forKey: .totalSessions) ?? 0
        overallLevel = try container.decodeIfPresent(Double.self, forKey: .overallLevel) ?? 1.0
        interestTopics = try container.decodeIfPresent([String: Double].self, forKey: .interestTopics) ?? [:]
        vocabularyStats = try container.decodeIfPresent([String: WordMastery].self, forKey: .vocabularyStats) ?? [:]
        pronunciationScores = try container.decodeIfPresent([String: Double].self, forKey: .pronunciationScores) ?? [:]
        preferredTeachingStyle = try container.decodeIfPresent(TeachingStyle.self, forKey: .preferredTeachingStyle) ?? .balanced
        
        vocabularyScore = try container.decodeIfPresent(Double.self, forKey: .vocabularyScore) ?? 0.2
        pronunciationScore = try container.decodeIfPresent(Double.self, forKey: .pronunciationScore) ?? 0.2
        grammarScore = try container.decodeIfPresent(Double.self, forKey: .grammarScore) ?? 0.2
        fluencyScore = try container.decodeIfPresent(Double.self, forKey: .fluencyScore) ?? 0.2
        
        streakCount = try container.decodeIfPresent(Int.self, forKey: .streakCount) ?? 0
        lastPracticeDate = try container.decodeIfPresent(Date.self, forKey: .lastPracticeDate)
        recentMistakes = try container.decodeIfPresent([Mistake].self, forKey: .recentMistakes) ?? []
        lastLessonSummary = try container.decodeIfPresent(String.self, forKey: .lastLessonSummary)
        lastLessonTopic = try container.decodeIfPresent(String.self, forKey: .lastLessonTopic)
        sessionHistory = try container.decodeIfPresent([SessionSummary].self, forKey: .sessionHistory) ?? []
        
        longTermMemory = try container.decodeIfPresent(String.self, forKey: .longTermMemory) ?? ""
        isInitialAssessmentComplete = try container.decodeIfPresent(Bool.self, forKey: .isInitialAssessmentComplete) ?? false
        teachingProgram = try container.decodeIfPresent(String.self, forKey: .teachingProgram)
        
        // NEW FIELDS: Default values for existing profiles
        currentLessonIndex = try container.decodeIfPresent(Int.self, forKey: .currentLessonIndex) ?? 1
        completedLessonTopics = try container.decodeIfPresent([String].self, forKey: .completedLessonTopics) ?? []
    }
    
    // Regular init for fresh profiles
    init() {}
}

/// Manages the persistence and updates of the LearnerProfile
@Observable
final class LearnerProfileManager {
    static let shared = LearnerProfileManager()
    private let profileKey = "jarvis_learner_profile"
    
    var currentProfile: LearnerProfile
    
    private init() {
        if let data = UserDefaults.standard.data(forKey: profileKey) {
            do {
                var profile = try JSONDecoder().decode(LearnerProfile.self, from: data)
                
                // MIGRATION: If we have sessions but assessment is not complete, fix it
                if profile.totalSessions > 0 && !profile.isInitialAssessmentComplete {
                    profile.isInitialAssessmentComplete = true
                }
                
                // MIGRATION: Ensure history exists
                if profile.sessionHistory == nil {
                    profile.sessionHistory = []
                }
                
                self.currentProfile = profile
            } catch {
                AppLogger.network.error("Profile decoding failed: \(error.localizedDescription). Creating fresh profile.")
                self.currentProfile = LearnerProfile()
            }
        } else {
            self.currentProfile = LearnerProfile()
        }
    }
    
    func save() {
        if let data = try? JSONEncoder().encode(currentProfile) {
            UserDefaults.standard.set(data, forKey: profileKey)
        }
    }
    
    func setAssessmentComplete() {
        currentProfile.isInitialAssessmentComplete = true
        save()
    }
    
    func updateStreak() {
        let calendar = Calendar.current
        let today = Date()
        
        guard let lastDate = currentProfile.lastPracticeDate else {
            currentProfile.streakCount = 1
            currentProfile.lastPracticeDate = today
            save()
            return
        }
        
        if calendar.isDateInYesterday(lastDate) {
            currentProfile.streakCount += 1
            currentProfile.lastPracticeDate = today
        } else if !calendar.isDateInToday(lastDate) {
            currentProfile.streakCount = 1
            currentProfile.lastPracticeDate = today
        }
        save()
    }
    
    func addMistake(original: String, correction: String, explanation: String) {
        let mistake = LearnerProfile.Mistake(original: original, correction: correction, explanation: explanation)
        currentProfile.recentMistakes.insert(mistake, at: 0)
        if currentProfile.recentMistakes.count > 10 {
            currentProfile.recentMistakes.removeLast()
        }
        save()
    }
    
    func updateMetrics(vocabulary: Double? = nil, pronunciation: Double? = nil, grammar: Double? = nil, fluency: Double? = nil) {
        if let v = vocabulary { currentProfile.vocabularyScore = v }
        if let p = pronunciation { currentProfile.pronunciationScore = p }
        if let g = grammar { currentProfile.grammarScore = g }
        if let f = fluency { currentProfile.fluencyScore = f }
        save()
    }
    
    func updateWord(word: String, wasSuccessful: Bool) {
        var mastery = currentProfile.vocabularyStats[word] ?? LearnerProfile.WordMastery()
        mastery.attempts += 1
        if wasSuccessful { mastery.successes += 1 }
        mastery.lastAttempt = Date()
        currentProfile.vocabularyStats[word] = mastery
        save()
    }
    
    func addTopicInterest(topic: String, weight: Double = 0.1) {
        let currentWeight = currentProfile.interestTopics[topic] ?? 0.0
        currentProfile.interestTopics[topic] = min(1.0, currentWeight + weight)
        save()
    }
    
    func updatePronunciation(language: String, score: Double) {
        let currentScore = currentProfile.pronunciationScores[language] ?? 0.5
        // Moving average to smooth spikes
        currentProfile.pronunciationScores[language] = (currentScore * 0.7) + (score * 0.3)
        save()
    }
    
    func addSessionSummary(topic: String, summary: String, successRate: Double) {
        let session = LearnerProfile.SessionSummary(
            id: UUID(),
            date: Date(),
            topic: topic,
            summary: summary,
            successRate: successRate
        )
        if currentProfile.sessionHistory == nil {
            currentProfile.sessionHistory = []
        }
        currentProfile.sessionHistory?.insert(session, at: 0)
        currentProfile.lastLessonSummary = summary
        currentProfile.lastLessonTopic = topic
        
        // Limit history size
        if let count = currentProfile.sessionHistory?.count, count > 20 {
            currentProfile.sessionHistory?.removeLast()
        }
        
        currentProfile.totalSessions += 1
        currentProfile.isInitialAssessmentComplete = true // Any summary marks assessment as complete
        save()
    }
    
    func addLongTermFact(_ fact: String) {
        if currentProfile.longTermMemory.isEmpty {
            currentProfile.longTermMemory = fact
        } else if !currentProfile.longTermMemory.contains(fact) {
            currentProfile.longTermMemory += "\n- \(fact)"
        }
        save()
    }
    
    func updateTeachingProgram(_ program: String) {
        currentProfile.teachingProgram = program
        save()
    }
    
    func advanceLesson(topic: String) {
        currentProfile.completedLessonTopics.append(topic)
        currentProfile.currentLessonIndex += 1
        save()
    }
    
    func resetCurriculum() {
        currentProfile.currentLessonIndex = 1
        currentProfile.completedLessonTopics = []
        currentProfile.teachingProgram = nil
        currentProfile.isInitialAssessmentComplete = false
        save()
    }
}
